

CONTAINER=document.getElementsByClassName("Laudo");

EXAMES=new Object;
EXAMES.quantidade=0;
EXAMESPORTIPO=new Object;


CONTAINER=document.getElementsByClassName("Laudo");

EXAMES=new Object;
EXAMES.quantidade=0;
EXAMESPORTIPO=new Object;

for(i=0;i<CONTAINER.length;i++){
EXAMES.quantidade++;
DATASTR=CONTAINER[i].getElementsByTagName('p')[0].innerHTML.match(/(\d{2})\/(\d{2})\/(\d{4})/gi);
if(EXAMES[DATASTR]){}else{EXAMES[DATASTR]=new Object};
CONTAINERB=CONTAINER[i].getElementsByTagName('b');
NOMEEXAMETEMP=CONTAINERB[0].innerHTML;
EXAMES[DATASTR][i]=new Object;
EXAMES[DATASTR][i].NOME_EXAME=NOMEEXAMETEMP;
RESULTADOEXAMETEMP=CONTAINERB[2].innerHTML;
EXAMES[DATASTR][i].RESULTADO_EXAME=RESULTADOEXAMETEMP;

if(EXAMESPORTIPO[NOMEEXAMETEMP]){
n_OBJ=EXAMESPORTIPO[NOMEEXAMETEMP].length+1;
EXAMESPORTIPO[NOMEEXAMETEMP][n_OBJ]=new Object;
EXAMESPORTIPO[NOMEEXAMETEMP][n_OBJ].DATAEXAMEPORTIPO=DATASTR;
EXAMESPORTIPO[NOMEEXAMETEMP][n_OBJ].RESULTADOEXAMEPORTIPO=RESULTADOEXAMETEMP;
}else{
EXAMESPORTIPO[NOMEEXAMETEMP]=new Object;
EXAMESPORTIPO[NOMEEXAMETEMP][0]=new Object;
EXAMESPORTIPO[NOMEEXAMETEMP][0].DATAEXAMEPORTIPO=DATASTR;
EXAMESPORTIPO[NOMEEXAMETEMP][0].RESULTADOEXAMEPORTIPO=RESULTADOEXAMETEMP;
}

}




alert(JSON.stringify(EXAMES[Object.keys(EXAMES)[1]]));
alert(JSON.stringify(EXAMESPORTIPO));
var xa=Object.keys(EXAMES)[1]+" --> ";
var q=EXAMES[Object.keys(EXAMES)[1]];

for (w=0;w<Object.keys(q).length;w++){
xa=xa+EXAMES[Object.keys(EXAMES)[1]][w].NOME_EXAME+" : "+EXAMES[Object.keys(EXAMES)[1]][w].RESULTADO_EXAME+" / ";
}
alert(xa);

void(0)
